name: Go Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
        
    - name: Install dependencies
      run: |
        cd error-demo
        go mod download
        
    - name: Build
      run: |
        cd error-demo
        go build -v ./...
        
    - name: Check formatting
      run: |
        cd error-demo
        go fmt ./...
        
    - name: Run vet
      run: |
        cd error-demo
        go vet ./...
        
    - name: Run tests
      run: |
        cd error-demo
        go test -v ./...
        
    - name: Build binary
      run: |
        cd error-demo
        go build -o error-demo-bin