name: Build Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build_binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
        
    - name: Install dependencies
      run: |
        cd error-demo
        go mod download
        
    - name: Build for Linux
      run: |
        cd error-demo
        GOOS=linux GOARCH=amd64 go build -o error-demo-linux
        
    - name: Build for macOS
      run: |
        cd error-demo
        GOOS=darwin GOARCH=amd64 go build -o error-demo-macos
        
    - name: Build for Windows
      run: |
        cd error-demo
        GOOS=windows GOARCH=amd64 go build -o error-demo-windows.exe