name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Install dependencies
      run: |
        cd error-demo
        go mod download
        
    - name: Build for multiple platforms
      run: |
        mkdir -p builds
        
        # Build for Linux
        cd error-demo
        GOOS=linux GOARCH=amd64 go build -o ../builds/error-demo-linux-amd64
        
        # Build for macOS
        GOOS=darwin GOARCH=amd64 go build -o ../builds/error-demo-macos-amd64
        
        # Build for Windows
        GOOS=windows GOARCH=amd64 go build -o ../builds/error-demo-windows-amd64.exe
        
        cd ..
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          builds/error-demo-linux-amd64
          builds/error-demo-macos-amd64
          builds/error-demo-windows-amd64.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}